### ISSUE TITLE
Better handling of end-of-list removal

### ISSUE THREAD

**Issue by RayDar** [TonicArtos/SuperSLiM#70] opened 2015-04-08 01:14 UTC
If notifyDataSetChanged() is called when the user has scrolled to the end of a long list, and several rows at the end of the list have been removed, the new list is laid-out improperly. You get a list that is scrolled past the end, presenting just white space. You can drag-down on the white space area and the tail-end of the list scrolls back into view.

The Android LinearLayoutManager handles this case by scrolling the list back to the first position, which isn't ideal, but it is better than scrolled past the (new) end.

**Comment by TonicArtos** [comment] 2015-04-08 01:52
Hmm. I thought this was already handled. I'll look it.

**Comment by TonicArtos** [comment] 2015-04-08 16:05
Unfortunately, I won't be able to get on to this until next week. I expect to have a fix for it out in the next minor update next week. However, if you want to take a look at it yourself, please feel free. The affected method is most likely `isOverscrolled()`, barring that it may be `fixOverscroll()`. I'd say `isOverscrolled()` is simply not detecting the situation correctly.

**Comment by RayDar** [comment] 2015-04-09 22:17
The problem is in isOverscrolled(). Specifically, reachedBottom is false, which causes the method to return false. When isOverscrolled() is forced to return true anyway, the recyclerView is rendered properly.

I did some tests with keeping around the previous getPosition(lastVisibleView) and getPosition(firstVisibleView). In the case where it fails, the previous values are much higher than the current values. It seems there ought to be a test that can detect this situation.

**Comment by RayDar** [comment] 2015-04-09 22:24
The following code seems to help, but I am not sure that it is correct:

      final int last_position = getPosition(lastVisibleView);

      if (last_position < mPreviousLastPosition)
      {
         mPreviousLastPosition = last_position;
         return (true);
      }

      mPreviousLastPosition = last_position;

      boolean reachedBottom = (last_position == (itemCount - 1));

**Comment by TonicArtos** [comment] 2015-04-09 23:49
Hmm, I've thought about what you said. It occurs to me that `state.getItemCount()` might be reporting the number of items in your adapter before the item removal. This makes sense for the first call to `onLayoutChildren()` if the LayoutManager supported predictive animations, however, SuperSLiM doesn't yet set that to true so this could be a bug.

I think it would be interesting to know two things: 1) How many times does `onLayoutChildren()` get called after the notify action? 2) What value is `itemCount` in `isOverscrolled()` for each call of `onLayoutChildren()`. According to my understanding of the documentation there should be a single call of `onLayoutChildren()` and itemCount should equal the number of items in your adapter at the time of the notify call.

**Comment by TonicArtos** [comment] 2015-04-22 14:45
Unfortunately, I was sick last week so I didn't get until now to look at this. I've tried a number of variations on removing items and calling the various notification methods. I don't see the behaviour you have reported in v0.4.9. The new style item removal notification does have some incorrect animation due to caching errors in the gridSLM (#71).

**Comment by RayDar** [comment] 2015-04-22 18:32
The following change to the start of CountryNamesAdapter shows the problem. It gives you 5 seconds after the app starts to scroll to the end of the list. Then, the dataset is changed and notifyDataSet() is called.

When you are at the end of the list, you will see a mostly blank screen, with perhaps one country shown at the top, even though far more can fit.

/** Modified constructor */
 public CountryNamesAdapter(final Context context, int headerMode)
  {
      mContext = context;

      mHeaderDisplay = headerMode;

      mItems = new ArrayList<>();

      /** RayDar Debug code -- initially include all the items */
      setupItems(context, true);

      /** this gives the user 5 seconds to scroll to the end of the list (where the bug shows up) and then removes the first 20 items from the list */
      new Handler().postDelayed(new Runnable()
      {
         @Override
         public void run()
         {
            setupItems(context, false);
            notifyDataSetChanged();
         }
      }, 5000);
   }

   /**
    * RayDar Debug code -- setup mItems either as normal, or with the first 20 countries missing.
    * This simulates the underlying dataset suddenly changing due to events such as background cloud synchronization, or a filter being applied to the set.
    *
    * @param context ubiquitous Android context
    * @param all_items true when all countries should be there, false when the first 20 should be missing
    */
   private void setupItems(final Context context, final boolean all_items)
   {
      final String[] countryNames = context.getResources().getStringArray(R.array.country_names);

      /** offset of first country in countryNames to be included */
      final int offset = all_items ? 0 : 20;

      mItems.clear();

      String lastHeader = "";
      int sectionManager = -1;
      int headerCount = 0;
      int sectionFirstPosition = 0;
      for (int i = 0; i < countryNames.length-offset; i++)
      {
         String header = countryNames[i+offset].substring(0, 1);
         if (!TextUtils.equals(lastHeader, header))
         {
            // Insert new header view and update section data.
            sectionManager = (sectionManager + 1) % 2;
            sectionFirstPosition = i + headerCount;
            lastHeader = header;
            headerCount += 1;
            mItems.add(new LineItem(header, true, sectionManager, sectionFirstPosition));
         }
         mItems.add(new LineItem(countryNames[i+offset], false, sectionManager, sectionFirstPosition));
      }
   }

**Comment by TonicArtos** [comment] 2015-04-22 18:37
Oh I see. I was looking at removing items at the end of the list, not the start.

**Comment by TonicArtos** [comment] 2015-04-22 19:19
Okay. I'm not convinced the bug is in the overscroll correction. If you play around with removing different values you find slightly different behaviours on removing items from the beginning of the adapter. I am thinking it could be caused by a stale position for the anchor as calculated in `onLayoutChildren()`.

Anyway, I'll continue to look into this and get a fix out as soon as I can. Thank you for your help.

**Comment by RayDar** [comment] 2015-04-22 19:55
DOH! I I should have named this "better start-of-list removal while viewing end-of-list".

Glad to see that you are well again.

**Comment by TonicArtos** [comment] 2015-04-23 15:42
I have put up a snapshot with a fix for this. It isn't perfect because recycler view doesn't allow layout managers to use ids to track views. Basically everything will be much better when we can use notify item removed, which I have to finish... argh!

I'll put out the snapshot for release tomorrow if I don't hear about any more bugs to fix.

**Closed** 2015-04-24 17:49 UTC
Labels: confirmed
