### ISSUE TITLE
onCreateViewHolder is being spammed again

### ISSUE THREAD

**Issue by kcorwin** [TonicArtos/SuperSLiM#50] opened 2015-03-03 13:38 UTC
I noticed this after updating to the 0.4.0 release - onCreateViewHolder gets called rapidly on scroll. Reverting to 0.2.4 fixes it.

I'm assuming this is a regression of either issue #15 or issue #13 or both.

**Comment by TonicArtos** [comment] 2015-03-03 13:44
Thanks, it seems to be related to #15 when scrolling down.

**Comment by TonicArtos** [comment] 2015-03-03 13:45
Actually it is a tiny bit weird that it only crops up on the first scroll over the grid's header, but I'll fix it anyway :)

**Comment by TonicArtos** [comment] 2015-03-03 14:01
Regression was introduced in 579a591d. Should be finding the header before getting a new one.

**Comment by TonicArtos** [comment] 2015-03-03 14:28
Okay, so I've pushed this out in a v0.4.4-SNAPSHOT. I've decided to sit on this for a day in case any other bugs get reported in that time.

**Comment by TonicArtos** [comment] 2015-03-03 14:31
I will close this manually when v0.4.4 is published.

**Comment by kcorwin** [comment] 2015-03-03 16:20
This does the trick - thanks! And impressive turn-around time. :)

**Comment by TonicArtos** [comment] 2015-03-03 16:23
Though debugging views isn't the easiest, finding the bugged code for this kind of problem is easy. Also, I think this is the last of the caching and recycle errors for view handling. In master:HEAD I have gone and cached the section data too so there should be a less view binding too.

**Comment by TonicArtos** [comment] 2015-03-04 12:08
...and v0.4.4 is out.

**Closed by TonicArtos** 2015-03-04 12:08 UTC
Labels: bug, confirmed
