### ISSUE TITLE
IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by muresanb** [TonicArtos/SuperSLiM#86] opened 2015-05-04 11:29 UTC
at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4243)
at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:4193)
at com.tonicartos.superslim.LayoutState.recycleCache(LayoutState.java:52)
at com.tonicartos.superslim.LayoutManager.scrollVerticallyBy(LayoutManager.java:367)
at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3458)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
at android.view.Choreographer.doCallbacks(Choreographer.java:590)
at android.view.Choreographer.doFrame(Choreographer.java:559)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5834)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by muresanb** [comment] 2015-05-04 11:33
I'm using 2 view types, one for the section header, and one for the list items.
```java
   @Override
    public int getItemViewType(Cursor cursor) {
        return ContactsSectionsCursorWrapper.isSectionHeader(cursor) ? VIEW_TYPE_HEADER : VIEW_TYPE_NORMAL;
    }
```
setting layout params in bind method:
```java
        lp.headerDisplay =LayoutManager.LayoutParams.HEADER_STICKY;
        lp.isHeader = thisIsHeader;
        lp.setSlm(LinearSLM.ID);
        lp.setFirstPosition(firstPositionInSection);
```

All works fine and it appears that at some point, when the 5'th section is displayed (about 20-30 items per section) the app crashes. It crashes at the same list item every time.

**Comment by TonicArtos** [comment] 2015-05-04 21:35
This seems to come up from time to time, typically it is caused by a view having the wrong first position. However, I think it is probably past time to add optional logging to the library to help diagnose these problems.

**Comment by TonicArtos** [comment] 2015-05-08 18:06
@muresanb I've been writing tests for the library and I still haven't come across any problems here. Did you check that the item it is getting stuck on has the correct section first position set?

**Comment by itlonewolf** [comment] 2015-05-27 06:57
I have this problem,and my adapter is 
```
public class WorkListAdapter extends RecyclerView.Adapter<AWorksViewHolder> {


    private static final int VIEW_TYPE_HEADER = 0x01;

    private static final int VIEW_TYPE_CONTENT = 0x00;

    private static final int LINEAR = 0;

    private List<ALineItem> mLineItems;
    private Context mContext ;

    public WorkListAdapter(Context context){
        mContext = context;
    }


    public void fillData(List<Work> workList) {
        if (mLineItems == null) {
            mLineItems = new ArrayList<>();
        }

        int headerCount = 0;
        int sectionFirstPostion = 0;
        for (int i = 0; i < workList.size(); i++) {
            Work work = workList.get(i);
            if (work == null) {
                continue;
            }


            //header
            sectionFirstPostion = i + headerCount;
            headerCount += 1;
            mLineItems.add(new LineItemHeader(sectionFirstPostion, work));
            LogCus.d("header name >>>" + work.getActivity_name());

            //item
            List<UGCInfo> ugcInfos = work.getTopic_info_list();
            if (ugcInfos == null || ugcInfos.size() == 0) {
                continue;
            }
            for (int iUGC = 0; iUGC < ugcInfos.size(); iUGC++) {
                UGCInfo ugcInfo = ugcInfos.get(iUGC);
                if (ugcInfo == null) {
                    continue;
                }
                mLineItems.add(new LineItemUGCInfo(sectionFirstPostion, ugcInfo));
            }
        }
        LogCus.d("mLineItems>>" + mLineItems);
    }

    @Override
    public AWorksViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view;
        switch (viewType) {
            case VIEW_TYPE_HEADER:
                view = LayoutInflater.from(mContext).inflate(R.layout.header_item, parent, false);
                return new WorksHeaderViewHolder(view, mContext);
            case VIEW_TYPE_CONTENT:
                view = LayoutInflater.from(mContext).inflate(R.layout.iyd_works_profile_item, parent, false);
                return new UGCInfoViewHolder(view, mContext);
        }
        return null;

    }

    @Override
    public void onBindViewHolder(final AWorksViewHolder viewHolder, final int pos) {

        if (mLineItems == null || mLineItems.size() == 0) {
            return;
        }
        final ALineItem lineItem = mLineItems.get(pos);
        final View itemView = viewHolder.itemView;

        if (lineItem != null) {
            final GridSLM.LayoutParams params = GridSLM.LayoutParams.from(itemView.getLayoutParams());

            if (lineItem.isHeader) {
                Work work = lineItem.mWork;
                viewHolder.bindItem(work);

                if (params.isHeader) {
//                    params.headerDisplay = GridSLM.LayoutParams.HEADER_INLINE | GridSLM.LayoutParams.HEADER_STICKY;
                    params.width = ViewGroup.LayoutParams.MATCH_PARENT;
                }

            } else {
                UGCInfo ugcInfo = lineItem.mUgcInfo;
                viewHolder.bindItem(ugcInfo);

            }


            params.headerEndMarginIsAuto = true;
            params.headerStartMarginIsAuto = true;
            params.setSlm(GridSLM.ID);
//            params.setSlm(LinearSLM.ID);
            params.setFirstPosition(lineItem.mSectionFirstPos);
            params.setNumColumns(3);

            itemView.setLayoutParams(params);

        }
    }

    @Override
    public int getItemViewType(int position) {
        ALineItem lineItem = mLineItems.get(position);

//        assert (lineItem != null);

        int viewType;
        if (lineItem.isHeader) {
            viewType = VIEW_TYPE_HEADER;
        } else {
            viewType = VIEW_TYPE_CONTENT;
        }
        return viewType;
    }

    @Override
    public int getItemCount() {
        if (mLineItems == null || mLineItems.size() == 0) {
            return 0;
        }

        return mLineItems.size();
    }

    public abstract class ALineItem implements Serializable{
        public boolean isHeader = false;

        public abstract boolean isHeader();

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            ALineItem lineItem = (ALineItem) o;

            if (mUid != lineItem.mUid) return false;
            return mRaceId == lineItem.mRaceId;

        }

        @Override
        public int hashCode() {
            int result = mUid;
            result = 31 * result + mRaceId;
            return result;
        }

        public int mSectionFirstPos = -1;

        public UGCInfo mUgcInfo;
        public Work mWork;


        public String mHeaderName;
        public String mCoverImgUrl;
        public int mUid ;
        public int mRaceId ;
    }

    public class LineItemUGCInfo extends ALineItem{

        public LineItemUGCInfo(int sectionFirstPos, UGCInfo ugcInfo){
            this.mSectionFirstPos = sectionFirstPos;
            this.mUgcInfo = ugcInfo;
            this.mCoverImgUrl = ugcInfo.getPic_url();
            this.mUid = ugcInfo.getUid();
            this.isHeader = false;
        }


        @Override
        public boolean isHeader() {
            return false;
        }
    }

    public class LineItemHeader extends ALineItem{
        public LineItemHeader(int sectionFirstPos, Work work){
            this.mSectionFirstPos = sectionFirstPos;
            this.mWork = work;
            this.mHeaderName = work.getActivity_name();
            this.mRaceId = work.getActivity_id();
            this.isHeader = true;
        }

        @Override
        public boolean isHeader() {
            return true;
        }
    }
}
```
and the  Work class:
```
public class Work implements Serializable {
    private int activity_id;
    private int hasStory;
    private String activity_name;
    private List<UGCInfo> topic_info_list;
    private static final int HasStory = 1;
    private static final int HasntStory = 0;

}
```

and the AWorksViewHolder:
```
public abstract class AWorksViewHolder extends RecyclerView.ViewHolder {

    public int getType(){
        return -1;
    }

    public AWorksViewHolder(View itemView) {
        super(itemView);
    }

    public abstract void bindItem(Serializable info);

}
```
and the UGCInfoViewHolder
```
public class UGCInfoViewHolder extends AWorksViewHolder {
    private ImageView mIvCoverImg;
    private ImageView mIvTagIsStoryOrNot;
    private ImageView mIvTagIsVideoOrNot;
    private Context mContext;

    public UGCInfoViewHolder(View itemView, Context context) {
        super(itemView);
        this.mContext = context;
        mIvCoverImg = ViewsUtil.find(itemView, R.id.ivCoverImgUgcWorksProfileFragment);
        mIvTagIsStoryOrNot = ViewsUtil.find(itemView, R.id.ivTagIsStoryOrNotWorksProfileFragment);
        mIvTagIsVideoOrNot = ViewsUtil.find(itemView, R.id.ivTagIsVideoWorksProfileFragment);
    }


    public void bindItem(Serializable info) {
        final UGCInfo ugcInfo;
        if (info instanceof UGCInfo) {
            ugcInfo = (UGCInfo) info;
        } else {
            return;
        }
        //cover img
        ImageUtils.showImgViaNet(mIvCoverImg, ugcInfo.getTitle_page(), R.mipmap.background, R.mipmap.background);
                //enter ugcinfo page
        mIvCoverImg.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intentUgcDetail = new Intent(mContext, UGCDetailActivity.class);
                intentUgcDetail.putExtra(UGCDetailActivity.TAG_UGC_Detail, ugcInfo);
                mContext.startActivity(intentUgcDetail);
            }
        });

        if (ugcInfo.isStory()) {
            mIvTagIsStoryOrNot.setVisibility(View.VISIBLE);
        } else {
            mIvTagIsStoryOrNot.setVisibility(View.GONE);
        }

        if (ugcInfo.isVideo()) {
            mIvTagIsVideoOrNot.setVisibility(View.VISIBLE);
        } else {
            mIvTagIsVideoOrNot.setVisibility(View.GONE);
        }
    }
}
```
and the WorksHeaderViewHolder
```
public class WorksHeaderViewHolder extends AWorksViewHolder {
    private Context mContext ;
    private TextView mTvHeaderTitle;

    public WorksHeaderViewHolder(View itemView, Context context) {
        super(itemView);
        this.mContext  = context;
        this.mTvHeaderTitle = ViewsUtil.find(itemView, R.id.tvHeaderTitleProfileFragment);
    }

    @Override
    public void bindItem(Serializable info) {
        final Work work;
        if (info instanceof Work) {
            work = (Work) info;
        } else {
            return;
        }
        //set header text
        mTvHeaderTitle.setText(work.getActivity_name());
        //jump
        mTvHeaderTitle.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent raceDetailIntent = new Intent(mContext, RaceDetailsActivity.class);
                raceDetailIntent.putExtra(RaceDetailsActivity.TAG, work.getActivity_id());
                mContext.startActivity(raceDetailIntent);
            }
        });
    }
}
```

**Comment by itlonewolf** [comment] 2015-05-27 07:43
![looks like this](https://github.com/itlonewolf/Android-ParallaxHeaderViewPager_ScrollView/blob/master/header.png)

**Comment by Studentessa** [comment] 2015-06-12 09:59
I also run into this problem, and as @TonicArtos said it was caused because I was setting wrong first position section. Check that!

**Comment by ChrisDolge** [comment] 2015-09-17 07:41
Hi, 

i also run into this problem , but a have to add items to the line item  dynamically. 

Any suggestion?

**Comment by JadenGu** [comment] 2015-11-23 11:28
Run into the same problem...

**Comment by jimmyntu** [comment] 2015-11-24 05:17
I had similar error. But I in the end, my problem is not because of bug. I set the setFirstPosition(sectionHeaderPos) wrongly. Not sure about other's problem

**Comment by JadenGu** [comment] 2015-11-24 06:04
@jimmyntu How do you set that position wrongly?

**Comment by JadenGu** [comment] 2015-11-24 06:04
@jimmyntu How do you set that position wrongly?

**Comment by JadenGu** [comment] 2015-11-24 06:05
@jimmyntu How do you set that position wrongly?

**Comment by JadenGu** [comment] 2015-11-24 06:05
https://github.com/jimmyntu How do you set that position wrongly?

**Comment by jimmyntu** [comment] 2015-11-24 08:56
@JadenGu I made mistake for set the section item pointing to non-section header pos. That shows me the error. If you look at the example app, and dump the value for setting each item's setFirstPosition value, you will see. Btw, My problem might not be related to the bug reported by others. There are only 2 sections in my list and 10+ items in each section.

**Comment by JadenGu** [comment] 2015-11-24 09:12
Thanks. @jimmyntu . It's indeed the position issue. My recycler view has a little bit complex. it's has loading more function and pulldown refresh. finally I figured out the write position and solved the problem.

**Comment by mobiRic** [comment] 2016-03-07 07:38
Regarding the "wrong first position section" comment, could you please explain what you mean.

I am also experiencing this issue, and am having trouble trying to figure out why any of my sections would have a wrong position.

Is there any known workaround for this yet, or a fix pending?

**Comment by MistaGreen** [comment] 2016-03-15 02:40
Let me add another possible fix for this kind of issue, please. I used MatrixCursor to set data to RecyclerViewCursorAdapter. The reason for this issue was ID columns equals to 0 for all headers. Hope that would help someone to save couple days of debugging.

**Comment by xiewenfeng** [comment] 2016-07-23 06:25
I have also encounted this problem, but my problem is not the upper circs. It is I have cleared the list data, but I did not call notifyDataChanged before call recyclerView.refreshComplete();.
when I call notifyDataChanged, then the question have resolved.

**Comment by webblong** [comment] 2016-12-07 07:27
@JadenGu Could you give me one example app source with the pullToRefresh/pullDownLoadMore and stickyHeaders ?
 I've been on it for 3 days , and stuck in this issue. I've no idea how to fix it.
Thank you.

**Closed** 2017-03-23 23:31 UTC
Labels: invalid
