### ISSUE TITLE
Sticky header appears below items

### ISSUE THREAD

**Issue by kolbasan** [TonicArtos/SuperSLiM#100] opened 2015-06-05 23:51 UTC
My recyclerview consits of 2 layouts, card view items and header text views.
The header is set to sticky|inline.
When I start scrolling the sticky textview is sliding under the card items in each section.
Am I just missing something, or this is an issue?

Thank you in advanced for you help!

**Comment by TonicArtos** [comment] 2015-06-06 00:02
Hi, this is a duplicate of #48. A workaround is to set the header elevation to be the same as the cards, 2dp. There is a possible solution in the works.

**Closed by TonicArtos** 2015-06-06 00:02 UTC
Labels: duplicate

**Comment by kolbasan** [comment] 2015-06-06 00:18
Your response was super fast, and solve my issue!
Thank you!!
