### ISSUE TITLE
findFirstVisibleItemPosition() was not found in LayoutManager

### ISSUE THREAD

**Issue by laiis** [TonicArtos/SuperSLiM#21] opened 2015-02-11 07:52 UTC
Sir.

I want to implement "Load More" via SuperSLiM

like this:

mRecyclerView.setOnScrollListener(new RecyclerView.OnScrollListener() {

    @Override
    public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
        super.onScrolled(recyclerView, dx, dy);

        visibleItemCount = mRecyclerView.getChildCount();
        totalItemCount = mLayoutManager.getItemCount();
        firstVisibleItem = mLayoutManager.findFirstVisibleItemPosition();

        if (loading) {
            if (totalItemCount > previousTotal) {
                loading = false;
                previousTotal = totalItemCount;
            }
        }
        if (!loading && (totalItemCount - visibleItemCount) 
            <= (firstVisibleItem + visibleThreshold)) {
            // End has been reached

            Log.i("...", "end called");

            // Do something

            loading = true;
        }
    }});

but there is no the method "mLayoutManager.findFirstVisibleItemPosition()",

How can I get the "firstVisibleItem" to implements "Load More",

or are there other ways to resovle my question?

Thank you~

**Comment by TonicArtos** [comment] 2015-02-12 04:19
Duplicate of #22.

**Closed by TonicArtos** 2015-02-12 04:19 UTC
Labels: duplicate, enhancement

**Comment by TonicArtos** [comment] 2015-02-17 12:07
Just to let you know. Fixed in v0.2.1.
