### ISSUE TITLE
superslim layoutmanager provide loadmore method?

### ISSUE THREAD

**Issue by nightbear1009** [TonicArtos/SuperSLiM#19] opened 2015-02-11 04:19 UTC
hi,
I'm using superslim in my project but I face a big problem to load more item when i am scrolling to the end of my data. 

In recyclerview to trigger loadmore method we need Layoutmanger to tell us some infomation
for example 
 int lastVisibleItem = ((LinearLayoutManager) mLayoutManager).findLastVisibleItemPosition();
                int totalItemCount = mLayoutManager.getItemCount();
                //lastVisibleItem >= totalItemCount - 4 

                if (lastVisibleItem >= totalItemCount - 4 && dy > 0) {
                    loadPage(currentQueryMap);
                }

can you provide some method for me?  thanks

**Comment by TonicArtos** [comment] 2015-02-11 04:43
I don't see any problem with implementing the equivalent of [LinearLayoutManager.findLastVisibleItemPosition()](https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#findLastVisibleItemPosition()).

**Comment by nightbear1009** [comment] 2015-02-11 06:04
oh,  sorry for my mistake. I am using the wrong layoutmanager.
i will close this issue.  Thanks.

**Comment by TonicArtos** [comment] 2015-02-11 06:08
Hang on, I thought you wanted findLastVisibleItemPosition() implemented on SuperSLiM.LayoutManager.

**Comment by nightbear1009** [comment] 2015-02-12 03:51
yes, that's what I need.

**Comment by TonicArtos** [comment] 2015-02-12 04:19
Duplicate of #22.

**Closed by TonicArtos** 2015-02-12 04:19 UTC
Labels: duplicate, enhancement

**Comment by TonicArtos** [comment] 2015-02-17 12:07
Just to let you know. Fixed in v0.2.1.
