### ISSUE TITLE
Global settings for max columns or min columns at layoutmanager level.

### ISSUE THREAD

**Issue by kingargyle** [TonicArtos/SuperSLiM#87] opened 2015-05-04 20:12 UTC
In our app we used to use GridLayoutManager and it had the ability to set the max number of columns.  When the tablet would be rotated we would calculate the max number of columns and set this on the layout manager.   So when in landscape the app could calculate that there are 3 columns that can  fit, but in portrait mode, only 2.

When using SuperSLIM with the GridSLM section manager, when starting the app, it is correctly in 2 per the value we pass to the LayoutParams.   When rotating to landscape, it correctly goes to 3 columns.  However, when rotating back to Portraite, it is staying in 3 columns which is causing items to be squished or condensed.   

A work around for this, was in the onConfigurationChanged for our fragment, was to tell the adapter that the dataset had changed.  This forced a relayout with the correct two column layout.   Ideally, I'd like to be able to tell the layoutmanager directly that it should adjust the layout for the sections based on the new max columns parameter being passed by a configuration change.   Notifying the adapter that the dataset has changed when it really hasn't seems like a cludge.   It is a workable, solution for now though.

This is happening in 4.12, it also occurred in 4.10.1 which was the last version I tested with.

**Comment by TonicArtos** [comment] 2015-05-04 20:50
Hi, this is already fixed on the development branch, but I'll see if a fix is possible for 0.4. However, you may like to know GridSLM can also do the column count calculation for you. To use this either 1) call `setColumnWidth(int width)` on the grid layout params, or 2) use the following xml line in the view defining your grid layout params:

```java
    app:slm_grid_columnWidth="96dip"
```

**Comment by TonicArtos** [comment] 2015-05-08 18:00
@kingargyle Just curious here, did you try using setColumnWidth?

**Comment by kingargyle** [comment] 2015-05-08 19:16
Yeah, I'm using that when setting the LayoutParams, but that isn't available from onConfigurationChange in a fragment.  Since that is set on each of the views.   I've got it working well enough for now for our app with the work around I mentioned earlier, so I haven't revisited it since I got it working.

**Comment by TonicArtos** [comment] 2015-05-08 20:19
Ah, are you handling the configuration change from rotation yourself to stop your activity from being recreated? If this is the case then I think I know how this bug is happening, and it is probably a bug on the development branch too, contrary to what I said before.

**Comment by kingargyle** [comment] 2015-05-08 23:48
No, we were doing it to handle resetting the Max Grid Columns in the past when were were using the support GridLayoutManager.   I tried not doing anything onConfigurationChange, and letting GridSLM handle reconfiguring things, but ended up having to put in a notification that data set had changed to get things working when rotation occurred.   I'll try to get back to this, but currently working on another issue for work so not sure when I'll get back to looking at it.

Nothing else, it would be a good place to put some Tests around to make sure it is behaving as you expect.

**Comment by TonicArtos** [comment] 2015-05-09 02:15
Okay, thanks for your clarification.

**Comment by TonicArtos** [comment] 2015-05-09 17:14
Oh, I understand what the problem is. I still have these methods in the actual GridSLM class. Yeah, they aren't supposed to be there. It seems I forgot to clean them up when things were changed for v0.4. The GridSLM is supposed to be configured entirely through the layout params.

**Closed** 2015-05-09 19:46 UTC
Labels: bug
